Note:
------

-- After practicing DCL commands, you will loose access on all tables from EMP database.
-- To bring back that access, run below commands.

GRANT OWNERSHIP ON DATABASE EMP TO ACCOUNTADMIN REVOKE CURRENT GRANTS;

GRANT OWNERSHIP ON SCHEMA EMP.HRDATA TO ROLE ACCOUNTADMIN REVOKE CURRENT GRANTS; 
GRANT OWNERSHIP ON SCHEMA EMP.PUBLIC TO ROLE ACCOUNTADMIN REVOKE CURRENT GRANTS;

GRANT ALL ON ALL TABLES IN SCHEMA EMP.public TO ROLE ACCOUNTADMIN;
GRANT ALL ON ALL TABLES IN SCHEMA EMP.hrdata TO ROLE ACCOUNTADMIN;
GRANT ALL ON ALL VIEWS IN SCHEMA EMP.public TO ROLE ACCOUNTADMIN;
GRANT ALL ON ALL VIEWS IN SCHEMA EMP.hrdata TO ROLE ACCOUNTADMIN;

GRANT ROLE ADMINISTRATOR TO ROLE ACCOUNTADMIN;